### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by cintamani** [DEFRA/waste-carriers-acceptance-tests#250]
1. Happy path registration on new app (update existing features in bo_new)
2. Convictions and pending payments on new app (update existing features!)
3. Validation checks on each screen in registration
4. Reduce dependence on seeded data for all bo_new tests, e.g. renewals, copy cards
5. Find ways to speed up the test pack
6. Develop some standards for the tests!
7. Modularise standard elements from @journey.standard_page.rb (suggestion from Alan)

**Comment by andrewhick** [comment]
These are being raised as separate issues:

1. https://github.com/DEFRA/waste-carriers-acceptance-tests/issues/251
2. https://github.com/DEFRA/waste-carriers-acceptance-tests/issues/252
3. https://github.com/DEFRA/waste-carriers-acceptance-tests/issues/253
4. https://github.com/DEFRA/waste-carriers-acceptance-tests/issues/254
5. https://github.com/DEFRA/waste-carriers-acceptance-tests/issues/255
6. https://github.com/DEFRA/waste-carriers-acceptance-tests/issues/256
