### ISSUE TITLE
Write happy path registration on new app

### ISSUE THREAD

**Issue by andrewhick** [DEFRA/waste-carriers-acceptance-tests#251]
Goal: to create a happy path registration entirely through the new app, from the front office.

Suggestions:

- Start from lower tier, as it's simpler
- Take the registration steps in `view_details.feature` as a start point
- Use helper functions from `journey_helpers.rb`. Methods already exist for much of the journey in the new app.
- For any page objects and steps which are shared between front and back office, put them under a `journey` folder, to avoid duplication.
- Where methods don't exist, either rewrite a method from the old app (such as `old_select_lower_tier_options` or write a new method.
- Decide whether to move some of the existing back office tests to front office, or copy them
- Registration and renewal are currently split across several steps. Consider adding a single step to do a simple happy path registration.

**Comment by cintamani** [comment]
This is now done
