### ISSUE TITLE
Test validations during the registration journey

### ISSUE THREAD

**Issue by andrewhick** [DEFRA/waste-carriers-acceptance-tests#253]
Once the registration journey tests are completed, we should enhance the tests by testing the validations on each page.

Use what has been done for WEX for comparison, and apply this to the WCR journey:
[WEX helper functions to test validations](https://github.com/DEFRA/waste-exemptions-acceptance-tests/blob/main/features/support/validation_helpers.rb)

**Comment by cintamani** [comment]
This don't make sense to do until https://eaflood.atlassian.net/browse/RUBY-923 is completed 
Currently scheduled for next sprint :)

**Comment by andrewhick** [comment]
RUBY-923 is now done so this is unblocked :)
