### ISSUE TITLE
Reduce back office dependency on seeded data

### ISSUE THREAD

**Issue by andrewhick** [DEFRA/waste-carriers-acceptance-tests#254]
The test pack is large and takes a long time to run. Some of its complexity comes down to the reliance on seeded data. This causes some problems:

- If a test fails (which is common, usually because of a timeout), and it relies on seeded data, it is fiddly to re-tag the tests and reset the data to re-run the tests.
- Seeded data is not live-like, and does not allow the full set of functionality to be run against it.
- Only front office seeded data (CBDU2xx) is available on all environments. Back office seeded data is now (CBDU1xx). We would like to be able to run all tests on all environments.

As much as possible, we want the back office tests to run on a standalone basis.

The goal is for all tests in the `bo_new` folder to run without reliance on seeded data. In practice, this means completing one or more registrations at the start of each test and then using that data for the test.

The following back office tests currently rely on seeded data:

- `cease_and_revoke.feature`
- `order_cards.feature`
- `transfer.feature`
- `renewal_payments.feature`
- `assisted_digital_renewal.feature`
- `incomplete_registration_completed.feature`

**Comment by cintamani** [comment]
Let's set up a proper meeting time to have a conversation about possible solutions to this.
