### ISSUE TITLE
Find ways to speed up the test pack

### ISSUE THREAD

**Issue by andrewhick** [DEFRA/waste-carriers-acceptance-tests#255]
The full test pack currently takes around 69 minutes to run on vagrant. During this time there is an approximately 50% chance that at least one test will fail (often due to a timeout) and need to be re-run, which is cumbersome to manage.

While this time will reduce as we get rid of old backend tests, there are still ways we can look to improve the speed of the pack, for example:

- Look at the 'glue' between each step, especially where signing out and signing in again. Does this need to be done each time?
- If a test relies on navigating to a particular page, could this be replaced with a simple "visit URL" step to kick it off? As long as the navigation is tested at least once in the test suite, we don't need to repeat the navigation to each page.
- Is every test necessary or is there repetition?
- Personally I am happy with when/then/when/then type scenarios (although I know some test purists would advise against this), as they allow us to reuse data. Could more scenarios be merged together?

**Comment by andrewhick** [comment]
@cintamani are you happy we can close this now? The test suite has gone down from 69 minutes to 30 minutes which is amazing - thank you! I'll continue to make use of the API and seeding wherever possible :)

**Comment by cintamani** [comment]
I am super happy to close this! 🥳

**Comment by andrewhick** [comment]
Excellent, closing 🥇
