### ISSUE TITLE
Fix non-headless submit button issue

### ISSUE THREAD

**Issue by andrewhick** [DEFRA/waste-carriers-acceptance-tests#279]
I am currently only able to run the full test suite in headless mode because of a non-headless issue submitting on some `submit_button`s.

When I run a test which calls it, such as early on in `permissions.feature`, the button gets highlighted, but not clicked. This causes the next part of the step to fail. However, similar green buttons work in other parts of the test suite.

Tests which fail at the `submit_button` when running non-headlessly are:
* `permissions.feature` at `finance_payment_method_page.rb`
* `upper_tier.feature` at `company_name_page.rb`

Cinti has investigated it and it is working for her, so I suspect it is a problem on my vagrant build. For me, the tests consistently fail at this point.

I'd like to sort this if possible, as it's occasionally useful to run tests non-headlessly.

**Comment by timstone** [comment]
I think the design system work has fixed this, I can run the tests in the UI or headlessly locally or on CI
